### ISSUE TITLE
add linking between all data.. i,e. where a note is, link to it, storeTag -> link to it, vica versa

### ISSUE THREAD

**Issue by Shelrothman** [Q118/cartotype#12]
## Create links between:
- [x]  individual storeItemTag in noteList -> storeItem
- [x]  storeItemTag in note view -> storeItem
- [x]  note in storeItem shop -> note
  (little toggler to view..)
- [x]  note in storeItem admin (each step spot) -> note
- [x] #16

**Comment by Shelrothman** [comment]
noteList -> list items
set up the Link but need to actualky have a "storeItem" page to link to.. just like ho0w there is one for notes... perhaps it can be the editDetails page? hmm
OR perhaps an option in each listItem view/edit

**for now, just take it to the admin section**:
- [x]  add section in the details form for notes
- [x]  link to that details form standalone way
_could literally set it up like the form Step._

**Comment by Q118** [comment]
could literally set it up like the form Step.

**Comment by Shelrothman** [comment]
- [x] completely revamp routing first for the admin subRoute

- [x] in view details -> make the edit button take user to detail-step

**Comment by Shelrothman** [comment]
also change loike in the form the edit form, use the notes sybol and jsut say Notes. instead of attached notes.
