### ISSUE TITLE
UI | Render the storeItemTags logic to display

### ISSUE THREAD

**Issue by Shelrothman** [Q118/cartotype#2]
- [x] seperate type of tag by color
- [x] #11
- [x]  display in Note view mode
- [x] #26
- [x]  store : display on each storeItem Card in /Store -> hover over to view notes attached
- [x]  admin : edit : on each item in selectionList AND in the edit details part
     - i.e. each of the preview cards
- [x]  admin: preview
- [x] admin : add : add option in the deailForm to put them in there...
- [x] #9
 - [x] #12
- [x] #3

**Comment by Shelrothman** [comment]
- [x] turn the notes buttons into store buttons

**Comment by Q118** [comment]
- [ ] add linking between all data.. i,e. where a note is, link to it, vica versa

**Comment by Shelrothman** [comment]
also what about attaching the _tags_ to the store items?
